"""Export the validated Python rules; --check is the CI drift gate."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from implementation.age_of_chess.rules_loader import load_ruleset

rules = load_ruleset(str(ROOT / 'rulesets/default.yaml')).game.model_dump(by_alias=True)
text = '// Generated by web/scripts/export_rules.py. Edit rulesets/default.yaml.\n'
text += 'export const RULES = ' + json.dumps(rules, indent=2, ensure_ascii=False) + ';\n'
target = ROOT / 'web/src/rules.mjs'
if '--check' in sys.argv:
    if target.read_text() != text:
        raise SystemExit('Browser rules are stale. Run .venv/bin/python web/scripts/export_rules.py')
else:
    target.write_text(text)
