// Generated by web/scripts/export_rules.py. Edit rulesets/default.yaml.
export const RULES = {
  "name": "Age of Chess – Warfare",
  "version": 3,
  "attack_all_directions": true,
  "lone_commander_loses": true,
  "commander_retreat_limit": 3,
  "archer_return_fire": true,
  "same_type_stance": "guarded_center",
  "frontal_enemy_sidesteps": true,
  "cavalry_pass_single_ally": true,
  "board": {
    "rows": 8,
    "cols": 8,
    "attack_field_depth": 4
  },
  "minimal_loss": {
    "enabled": true,
    "preserve_order": [
      "R",
      "N",
      "B",
      "P",
      "Q"
    ]
  },
  "pieces": {
    "P": {
      "label": "Pikeman",
      "class": "pikeman",
      "move": {
        "steps": [
          [
            -1,
            -1
          ],
          [
            -1,
            0
          ],
          [
            -1,
            1
          ]
        ],
        "max_steps": 1,
        "attack_field_sideways": true,
        "last_rank_all_directions": true,
        "retreat_trigger": "none",
        "threat_radius": 1
      },
      "abilities": [],
      "value": 1.0
    },
    "N": {
      "label": "Cavalry",
      "class": "cavalry",
      "move": {
        "steps": [
          [
            -1,
            -1
          ],
          [
            -1,
            0
          ],
          [
            -1,
            1
          ]
        ],
        "max_steps": 2,
        "attack_field_sideways": true,
        "last_rank_all_directions": true,
        "retreat_trigger": "none",
        "threat_radius": 1
      },
      "abilities": [],
      "value": 3.0
    },
    "B": {
      "label": "Archer",
      "class": "archer",
      "move": {
        "steps": [
          [
            -1,
            -1
          ],
          [
            -1,
            0
          ],
          [
            -1,
            1
          ]
        ],
        "max_steps": 1,
        "attack_field_sideways": true,
        "last_rank_all_directions": true,
        "retreat_trigger": "none",
        "threat_radius": 1
      },
      "abilities": [
        {
          "name": "ranged",
          "range": 2,
          "targets": [
            "B",
            "P",
            "Q"
          ],
          "requires_stack_size": 1
        },
        {
          "name": "power_shot",
          "range": 2,
          "targets": [
            "N",
            "R"
          ],
          "requires_stack_size": 2
        }
      ],
      "value": 3.0
    },
    "R": {
      "label": "Heavy Infantry",
      "class": "heavy_infantry",
      "move": {
        "steps": [
          [
            -1,
            -1
          ],
          [
            -1,
            0
          ],
          [
            -1,
            1
          ]
        ],
        "max_steps": 1,
        "attack_field_sideways": true,
        "last_rank_all_directions": true,
        "retreat_trigger": "none",
        "threat_radius": 1
      },
      "abilities": [],
      "value": 5.0
    },
    "Q": {
      "label": "Priestess",
      "class": "priestess",
      "move": {
        "steps": [
          [
            -1,
            -1
          ],
          [
            -1,
            0
          ],
          [
            -1,
            1
          ]
        ],
        "max_steps": 1,
        "attack_field_sideways": true,
        "last_rank_all_directions": true,
        "retreat_trigger": "adjacent_enemy",
        "threat_radius": 1
      },
      "abilities": [
        {
          "name": "convert",
          "range": 1,
          "targets": [
            "P",
            "N",
            "B",
            "R"
          ],
          "requires_stack_size": 1
        }
      ],
      "value": 4.0
    },
    "K": {
      "label": "Commander",
      "class": "king",
      "move": {
        "steps": [
          [
            -1,
            -1
          ],
          [
            -1,
            0
          ],
          [
            -1,
            1
          ]
        ],
        "max_steps": 1,
        "attack_field_sideways": false,
        "last_rank_all_directions": true,
        "retreat_trigger": "nearby_enemy",
        "threat_radius": 2
      },
      "abilities": [],
      "value": 1000.0
    }
  },
  "combat": {
    "single": {
      "P": {
        "P": "stance",
        "N": "win",
        "B": "win",
        "R": "lose",
        "Q": "win",
        "K": "win"
      },
      "N": {
        "P": "lose",
        "N": "stance",
        "B": "win",
        "R": "win",
        "Q": "win",
        "K": "win"
      },
      "B": {
        "P": "lose",
        "N": "lose",
        "B": "stance",
        "R": "lose",
        "Q": "win",
        "K": "win"
      },
      "R": {
        "P": "win",
        "N": "lose",
        "B": "win",
        "R": "stance",
        "Q": "win",
        "K": "win"
      },
      "Q": {
        "P": "illegal",
        "N": "illegal",
        "B": "illegal",
        "R": "illegal",
        "Q": "mutual",
        "K": "win"
      },
      "K": {
        "P": "win",
        "N": "win",
        "B": "win",
        "R": "win",
        "Q": "win",
        "K": "win"
      }
    },
    "stacks": [
      {
        "attacker": "N",
        "top": "B",
        "bottom": "B",
        "outcome": [
          true,
          false,
          false
        ]
      },
      {
        "attacker": "N",
        "top": "R",
        "bottom": "*",
        "outcome": [
          false,
          true,
          true
        ]
      },
      {
        "attacker": "R",
        "top": "P",
        "bottom": "P",
        "outcome": [
          false,
          false,
          true
        ]
      }
    ]
  },
  "repetition_draw": 3
};
